#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::{Arc, RwLock};
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    AmbiguousRuntimeId(Option<AmbiguousRuntimeId_Args>),
    RemoveActiveRuntime(Option<RemoveActiveRuntime_Args>),
    RuntimeNotFound(Option<RuntimeNotFound_Args>),
    StagingFailed(Option<StagingFailed_Args>),
    UpdateFailed(Option<UpdateFailed_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::AmbiguousRuntimeId(v) => {
                write!(f, "org.avocado.Runtimes.AmbiguousRuntimeId: {:#?}", v)
            }
            ErrorKind::RemoveActiveRuntime(v) => {
                write!(f, "org.avocado.Runtimes.RemoveActiveRuntime: {:#?}", v)
            }
            ErrorKind::RuntimeNotFound(v) => {
                write!(f, "org.avocado.Runtimes.RuntimeNotFound: {:#?}", v)
            }
            ErrorKind::StagingFailed(v) => {
                write!(f, "org.avocado.Runtimes.StagingFailed: {:#?}", v)
            }
            ErrorKind::UpdateFailed(v) => write!(f, "org.avocado.Runtimes.UpdateFailed: {:#?}", v),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply { error: Some(t), .. }
                if t == "org.avocado.Runtimes.AmbiguousRuntimeId" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::AmbiguousRuntimeId(v),
                        Err(_) => ErrorKind::AmbiguousRuntimeId(None),
                    },
                    _ => ErrorKind::AmbiguousRuntimeId(None),
                }
            }
            varlink::Reply { error: Some(t), .. }
                if t == "org.avocado.Runtimes.RemoveActiveRuntime" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::RemoveActiveRuntime(v),
                        Err(_) => ErrorKind::RemoveActiveRuntime(None),
                    },
                    _ => ErrorKind::RemoveActiveRuntime(None),
                }
            }
            varlink::Reply { error: Some(t), .. }
                if t == "org.avocado.Runtimes.RuntimeNotFound" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::RuntimeNotFound(v),
                        Err(_) => ErrorKind::RuntimeNotFound(None),
                    },
                    _ => ErrorKind::RuntimeNotFound(None),
                }
            }
            varlink::Reply { error: Some(t), .. } if t == "org.avocado.Runtimes.StagingFailed" => {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::StagingFailed(v),
                        Err(_) => ErrorKind::StagingFailed(None),
                    },
                    _ => ErrorKind::StagingFailed(None),
                }
            }
            varlink::Reply { error: Some(t), .. } if t == "org.avocado.Runtimes.UpdateFailed" => {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::UpdateFailed(v),
                        Err(_) => ErrorKind::UpdateFailed(None),
                    },
                    _ => ErrorKind::UpdateFailed(None),
                }
            }
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_ambiguous_runtime_id(
        &mut self,
        r#id: String,
        r#candidates: Vec<String>,
    ) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.Runtimes.AmbiguousRuntimeId",
            Some(
                serde_json::to_value(AmbiguousRuntimeId_Args { r#id, r#candidates })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_remove_active_runtime(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.Runtimes.RemoveActiveRuntime",
            None,
        ))
    }
    fn reply_runtime_not_found(&mut self, r#id: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.Runtimes.RuntimeNotFound",
            Some(
                serde_json::to_value(RuntimeNotFound_Args { r#id })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_staging_failed(&mut self, r#reason: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.Runtimes.StagingFailed",
            Some(
                serde_json::to_value(StagingFailed_Args { r#reason })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_update_failed(&mut self, r#reason: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.Runtimes.UpdateFailed",
            Some(
                serde_json::to_value(UpdateFailed_Args { r#reason })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#ManifestExtension {
    pub r#name: String,
    pub r#version: String,
    pub r#imageId: Option<String>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#Runtime {
    pub r#id: String,
    pub r#manifestVersion: i64,
    pub r#builtAt: String,
    pub r#runtime: RuntimeInfo,
    pub r#extensions: Vec<ManifestExtension>,
    pub r#active: bool,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#RuntimeInfo {
    pub r#name: String,
    pub r#version: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct AmbiguousRuntimeId_Args {
    pub r#id: String,
    pub r#candidates: Vec<String>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct RemoveActiveRuntime_Args {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct RuntimeNotFound_Args {
    pub r#id: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct StagingFailed_Args {
    pub r#reason: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct UpdateFailed_Args {
    pub r#reason: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Activate_Reply {}
impl varlink::VarlinkReply for Activate_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Activate_Args {
    pub r#id: String,
}
#[allow(dead_code)]
pub trait Call_Activate: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_Activate for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct AddFromManifest_Reply {}
impl varlink::VarlinkReply for AddFromManifest_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct AddFromManifest_Args {
    pub r#manifestPath: String,
}
#[allow(dead_code)]
pub trait Call_AddFromManifest: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_AddFromManifest for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct AddFromUrl_Reply {}
impl varlink::VarlinkReply for AddFromUrl_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct AddFromUrl_Args {
    pub r#url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#authToken: Option<String>,
}
#[allow(dead_code)]
pub trait Call_AddFromUrl: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_AddFromUrl for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Inspect_Reply {
    pub r#runtime: Runtime,
}
impl varlink::VarlinkReply for Inspect_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Inspect_Args {
    pub r#id: String,
}
#[allow(dead_code)]
pub trait Call_Inspect: VarlinkCallError {
    fn reply(&mut self, r#runtime: Runtime) -> varlink::Result<()> {
        self.reply_struct(Inspect_Reply { r#runtime }.into())
    }
}
impl Call_Inspect for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct List_Reply {
    pub r#runtimes: Vec<Runtime>,
}
impl varlink::VarlinkReply for List_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct List_Args {}
#[allow(dead_code)]
pub trait Call_List: VarlinkCallError {
    fn reply(&mut self, r#runtimes: Vec<Runtime>) -> varlink::Result<()> {
        self.reply_struct(List_Reply { r#runtimes }.into())
    }
}
impl Call_List for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Remove_Reply {}
impl varlink::VarlinkReply for Remove_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Remove_Args {
    pub r#id: String,
}
#[allow(dead_code)]
pub trait Call_Remove: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_Remove for varlink::Call<'_> {}
#[allow(dead_code)]
pub trait VarlinkInterface {
    fn activate(&self, call: &mut dyn Call_Activate, r#id: String) -> varlink::Result<()>;
    fn add_from_manifest(
        &self,
        call: &mut dyn Call_AddFromManifest,
        r#manifestPath: String,
    ) -> varlink::Result<()>;
    fn add_from_url(
        &self,
        call: &mut dyn Call_AddFromUrl,
        r#url: String,
        r#authToken: Option<String>,
    ) -> varlink::Result<()>;
    fn inspect(&self, call: &mut dyn Call_Inspect, r#id: String) -> varlink::Result<()>;
    fn list(&self, call: &mut dyn Call_List) -> varlink::Result<()>;
    fn remove(&self, call: &mut dyn Call_Remove, r#id: String) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn activate(
        &mut self,
        r#id: String,
    ) -> varlink::MethodCall<Activate_Args, Activate_Reply, Error>;
    fn add_from_manifest(
        &mut self,
        r#manifestPath: String,
    ) -> varlink::MethodCall<AddFromManifest_Args, AddFromManifest_Reply, Error>;
    fn add_from_url(
        &mut self,
        r#url: String,
        r#authToken: Option<String>,
    ) -> varlink::MethodCall<AddFromUrl_Args, AddFromUrl_Reply, Error>;
    fn inspect(&mut self, r#id: String) -> varlink::MethodCall<Inspect_Args, Inspect_Reply, Error>;
    fn list(&mut self) -> varlink::MethodCall<List_Args, List_Reply, Error>;
    fn remove(&mut self, r#id: String) -> varlink::MethodCall<Remove_Args, Remove_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn activate(
        &mut self,
        r#id: String,
    ) -> varlink::MethodCall<Activate_Args, Activate_Reply, Error> {
        varlink::MethodCall::<Activate_Args, Activate_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Runtimes.Activate",
            Activate_Args { r#id },
        )
    }
    fn add_from_manifest(
        &mut self,
        r#manifestPath: String,
    ) -> varlink::MethodCall<AddFromManifest_Args, AddFromManifest_Reply, Error> {
        varlink::MethodCall::<AddFromManifest_Args, AddFromManifest_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Runtimes.AddFromManifest",
            AddFromManifest_Args { r#manifestPath },
        )
    }
    fn add_from_url(
        &mut self,
        r#url: String,
        r#authToken: Option<String>,
    ) -> varlink::MethodCall<AddFromUrl_Args, AddFromUrl_Reply, Error> {
        varlink::MethodCall::<AddFromUrl_Args, AddFromUrl_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Runtimes.AddFromUrl",
            AddFromUrl_Args { r#url, r#authToken },
        )
    }
    fn inspect(&mut self, r#id: String) -> varlink::MethodCall<Inspect_Args, Inspect_Reply, Error> {
        varlink::MethodCall::<Inspect_Args, Inspect_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Runtimes.Inspect",
            Inspect_Args { r#id },
        )
    }
    fn list(&mut self) -> varlink::MethodCall<List_Args, List_Reply, Error> {
        varlink::MethodCall::<List_Args, List_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Runtimes.List",
            List_Args {},
        )
    }
    fn remove(&mut self, r#id: String) -> varlink::MethodCall<Remove_Args, Remove_Reply, Error> {
        varlink::MethodCall::<Remove_Args, Remove_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Runtimes.Remove",
            Remove_Args { r#id },
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Box<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}
impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "# Runtime lifecycle management for Avocado Linux\ninterface org.avocado.Runtimes\n\ntype RuntimeInfo (\n    name: string,\n    version: string\n)\n\ntype ManifestExtension (\n    name: string,\n    version: string,\n    imageId: ?string\n)\n\ntype Runtime (\n    id: string,\n    manifestVersion: int,\n    builtAt: string,\n    runtime: RuntimeInfo,\n    extensions: []ManifestExtension,\n    active: bool\n)\n\n# List all available runtimes\nmethod List() -> (runtimes: []Runtime)\n\n# Add a runtime from a TUF repository URL (authToken: optional bearer token for protected endpoints)\nmethod AddFromUrl(url: string, authToken: ?string) -> ()\n\n# Add a runtime from a local manifest file\nmethod AddFromManifest(manifestPath: string) -> ()\n\n# Remove a staged runtime by ID (or prefix)\nmethod Remove(id: string) -> ()\n\n# Activate a staged runtime by ID (or prefix)\nmethod Activate(id: string) -> ()\n\n# Inspect a runtime's details\nmethod Inspect(id: string) -> (runtime: Runtime)\n\nerror RuntimeNotFound (id: string)\nerror AmbiguousRuntimeId (id: string, candidates: []string)\nerror RemoveActiveRuntime ()\nerror StagingFailed (reason: string)\nerror UpdateFailed (reason: string)\n"
    }
    fn get_name(&self) -> &'static str {
        "org.avocado.Runtimes"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "org.avocado.Runtimes.Activate" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Activate_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner
                        .activate(call as &mut dyn Call_Activate, args.r#id)
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "org.avocado.Runtimes.AddFromManifest" => {
                if let Some(args) = req.parameters.clone() {
                    let args: AddFromManifest_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.add_from_manifest(
                        call as &mut dyn Call_AddFromManifest,
                        args.r#manifestPath,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "org.avocado.Runtimes.AddFromUrl" => {
                if let Some(args) = req.parameters.clone() {
                    let args: AddFromUrl_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.add_from_url(
                        call as &mut dyn Call_AddFromUrl,
                        args.r#url,
                        args.r#authToken,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "org.avocado.Runtimes.Inspect" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Inspect_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.inspect(call as &mut dyn Call_Inspect, args.r#id)
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "org.avocado.Runtimes.List" => self.inner.list(call as &mut dyn Call_List),
            "org.avocado.Runtimes.Remove" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Remove_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.remove(call as &mut dyn Call_Remove, args.r#id)
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
